apiVersion: v1
kind: Pod
metadata:
  name: gpu
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  containers:
  - name: gpu
    image: nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu20.04
    # allow attach (which keeps container running)
    stdin: true
    # stdin is a tty
    tty: true
    resources:
      requests:
        cpu: "1000m"
      limits:
        cpu: "2000m"
        memory: 2Gi
        nvidia.com/gpu: 1
    env:
      # needed to trigger nvidia-container-runtime which makes gpus available
      # already present in nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu20.04
      # but added here for documentation
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: compute,utility
