apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python:3.9-slim
    # allow attach (which keeps container running)
    stdin: true
    # stdin is a tty
    tty: true
    resources:
      requests:
        cpu: "1000m"
      limits:
        cpu: "1000m"
  terminationGracePeriodSeconds: 300
